name: CI/CD Task-API (Fly.io)

on:
  push:
    branches: [ main ]
    paths:
      - 'task-api/**'

permissions:
  contents: read

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      FLY_APP: admoai-task-api-condore
      FLY_REGION: iad
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    defaults:
      run:
        working-directory: task-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go 1.24.2
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Run unit tests
        run: go test ./internal/task -v

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@v1
        with:
          version: 'latest' 

      - name: Ensure Fly app exists
        run: |
          # intenta "show", si falla (exit≠0) es porque no existe → la crea
          if ! flyctl apps show "${FLY_APP}" >/dev/null 2>&1; then
            flyctl apps create "${FLY_APP}"
          else
            echo "✔ App ${FLY_APP} ya existe, omito creación"
          fi



      - name: Deploy to Fly.io
        run: |
          flyctl deploy \
            --app $FLY_APP \
            --regions $FLY_REGION \
            --remote-only
