name: CI/CD Task-API (Fly.io)

on:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  FLY_APP: task-api
  FLY_REGION: iad

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: task-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go 1.24.2
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Run unit tests
        run: go test ./internal/task -v

      - name: Install Fly CLI
        uses: superfly/flyctl-actions@1.1
        with:
          version: 'latest'

      - name: Authenticate to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth token

      - name: Ensure Fly app exists
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if ! flyctl apps list | grep -qx "${FLY_APP}"; then
            flyctl apps create "${FLY_APP}" --region "${FLY_REGION}"
          fi

      - name: Deploy to Fly.io
        run: |
          flyctl deploy \
            --app $FLY_APP \
            --region $FLY_REGION \
            --remote-only
